enum DateFormatType {
  DATE_TIME_SECONDS = 'HH:mm:ss',
  FULL_DATE_TIME_SECONDS = 'YYYY-MM-DD HH:mm:ss',
  FULL_DATE_TIME_MINUTE = 'YYYY-MM-DD HH:mm',
  MERIDIEM_FULL_DATE_TIME_MINUTE = 'YYYY-MM-DD A hh:mm',
  DOT_FULL_DATE_TIME_MINUTE = 'YYYY.MM.DD hh:mm',
  DOT_MERIDIEM_FULL_DATE_TIME_MINUTE = 'YYYY.MM.DD A hh:mm',
  DOT_YEAR_MONTH_DATE = 'YYYY.MM.DD',
  DASH_YEAR_MONTH_DATE = 'YYYY-MM-DD',
  SLASH_YEAR_MONTH_DATE = 'YYYY/MM/DD',
  SLASH_YEAR_MONTH = 'YYYY/MM',
  MATERIAL_DATE_YEAR_MONTH_DATE = 'YYYY-MM-dd',
  DASH_YEAR_MONTH = 'YYYY-MM',
  EN_YEAR_MONTH = 'MM/YYYY',
  KO_YEAR = 'YYYY년',
  KO_YEAR_MONTH = 'YYYY년 MM월',
  COMPACT_FULL_DATE_TIME_MINUTE = 'YYYYMMDDHHmm',
  MERIDIEM_DATE_TIME_MINUTE = 'A h:mm',
  COMPACT_MERIDIEM_FULL_DATE_TIME_MINUTE = 'YYYYMMDDHHmm A hh:mm',
}

export default DateFormatType;
